# Generated by Django 5.1.5 on 2025-01-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(),
        ),
    ]
